spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/board?serverTimezone=UTC&characterEncoding=UTF-8
    username: creed
    password: test
  jpa:
    defer-datasource-initialization: true
    open-in-view: false
    show-sql: true

    #    database-platform: org.hibernate.dialect.MySQL8Dialect
    #    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    #    database-platform: org.hibernate.dialect.H2Dialect

    hibernate:
      ddl-auto: create
    #      naming:
    #        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    #        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 1000
  sql:
    init:
      data-locations: classpath:data.sql
      mode: always
  h2:
    console:
      enabled: true
      path: /h2-console

logging:
  level:
    p6spy: DEBUG
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
      springframework:
        web:
          servlet: debug
    com.creedboy.springbootboard: debug

decorator:
  datasource:
    p6spy:
      enable-logging: true
      multiline: false
      logging: slf4j

debug: false

management.endpoint.web.exposure.include: "*"

---

#spring:
#  config:
#    activate:
#      on-profile: testdb
#  datasource:
#    url: jdbc:h2:mem:board;mode=mysql
#    driver-class-name: org.h2.Driver
#  sql:
#    init:
#      mode: always
#  test:
#    database:
#      replace: none