server:
  port: 5555

spring:
#  main:
#    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:mysql://localhost:3306/board?useUnicode=true&characterEncoding=utf8
    username: creed
    password: test
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
#    database: mysql
    #    database-platform: org.hibernate.dialect.MySQL8Dialect
#    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    #    show-sql: true
    hibernate:
      #      ddl-auto: create
      ddl-auto: update
#      naming:
#        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    properties:
      hibernate:
        #        show-sql: true
        format_sql: true
        enable_lazy_load_no_trans: false
        #        use_sql_comments: true
        default_batch_fetch_size: 100
#    defer-datasource-initialization: true
#  h2:
#    console:
#      enabled: false
#  sql.init.mode: always

logging:
  level:
    #    root: DEBUG
    #    p6spy: DEBUG
    org.hibernate.SQL: OFF
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

    org.springframework.jdbc.core.JdbcTemplate: DEBUG
    org.springframework.jdbc.core.StatementCreatorUtils: DEBUG
    org.springframework.jdbc.datasource.SimpleDriverDataSource: DEBUG
    i.a.a.c: ERROR

decorator:
  datasource:
    p6spy:
      enable-logging: true
      multiline: false
      logging: slf4j